"""Step 2c: expand the fraud address seed list from all Forta labelled-datasets.

Downloads all three Forta CSV files (phishing_scams, malicious_smart_contracts,
etherscan_malicious_labels), unions the addresses, deduplicates against the
existing FRAUD_ADDRESSES seed, and rewrites data/addresses/fraud_addresses.py
with the merged result.

Run this script whenever you want to refresh the fraud seed list.
No API key required — all sources are public GitHub raw files.
"""
from __future__ import annotations

import argparse
import io
import logging
import sys
import textwrap
from pathlib import Path

import pandas as pd
import requests

import _bootstrap  # noqa: F401

from config import FORTA_URLS
from data.addresses import FRAUD_ADDRESSES

log = logging.getLogger("02c_fetch_fraud_addresses")

# Mapping of each CSV's address column name
_ADDR_COLS = {
    "phishing_scams.csv": "address",
    "malicious_smart_contracts.csv": "contract_address",
    "etherscan_malicious_labels.csv": "banned_address",
}


def fetch_all_forta_addresses() -> list[str]:
    """Download every Forta CSV and return a deduplicated list of lowercased addresses."""
    all_addresses: set[str] = set()
    for filename, url in FORTA_URLS.items():
        log.info("Fetching %s ...", filename)
        try:
            resp = requests.get(url, timeout=30)
            resp.raise_for_status()
        except requests.RequestException as exc:
            log.warning("Failed to fetch %s: %s — skipping", filename, exc)
            continue

        df = pd.read_csv(io.StringIO(resp.text))

        # Determine address column: prefer known mapping, fall back to any col
        # whose name contains "address"
        col = _ADDR_COLS.get(filename) or next(
            (c for c in df.columns if "address" in c.lower()), None
        )
        if col is None or col not in df.columns:
            log.warning("Cannot find address column in %s (columns: %s)", filename, list(df.columns))
            continue

        addrs = df[col].dropna().astype(str).str.lower().str.strip().unique()
        log.info("  %s: %d addresses", filename, len(addrs))
        all_addresses.update(addrs)

    return sorted(all_addresses)


def write_fraud_addresses(addresses: list[str], out_path: Path) -> None:
    """Rewrite fraud_addresses.py with the merged address list."""
    lines = ',\n    '.join(f"'{a}'" for a in addresses)
    content = textwrap.dedent(f'''\
        """Seed list of fraudulent Ethereum contract addresses.

        This is the second of the two seed arrays that drive the data-collection
        pipeline. It corresponds to the paper\'s "Golden List": contract addresses
        publicly attributed to phishing campaigns, Ponzi schemes, smart-contract
        exploits, or rug pulls.

        The canonical ground truth for fraud labels in this project is the Forta
        Network labelled-datasets release, which is downloaded at runtime by
        ``scripts/02_fetch_labels.py``. This file is auto-generated by
        ``scripts/02c_fetch_fraud_addresses.py`` — do not edit by hand.

        Sources (all Forta Network labelled-datasets, labels/1/):
          - phishing_scams.csv
          - malicious_smart_contracts.csv
          - etherscan_malicious_labels.csv

        Addresses are stored lowercased to match Forta and Etherscan conventions.
        """
        from __future__ import annotations

        FRAUD_ADDRESSES: list[str] = [
            {lines},
        ]
    ''')
    out_path.write_text(content)
    log.info("Wrote %d addresses to %s", len(addresses), out_path)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Print stats without writing the file.",
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()

    forta_addrs = fetch_all_forta_addresses()
    log.info("Total unique addresses across all Forta CSVs: %d", len(forta_addrs))

    existing = set(a.lower() for a in FRAUD_ADDRESSES)
    new_addrs = [a for a in forta_addrs if a not in existing]
    log.info("New addresses not already in seed list: %d (existing: %d)", len(new_addrs), len(existing))

    merged = sorted(set(forta_addrs) | existing)
    log.info("Merged fraud address count: %d", len(merged))

    if args.dry_run:
        log.info("Dry run — skipping file write.")
        print(f"Would write {len(merged)} addresses ({len(new_addrs)} new from Forta).")
        return

    out_path = Path(__file__).resolve().parent.parent / "data" / "addresses" / "fraud_addresses.py"
    write_fraud_addresses(merged, out_path)
    print(f"Done. {len(merged)} total fraud addresses ({len(new_addrs)} added from Forta).")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, stream=sys.stderr)
    main()
