"""Regenerate the paper figures that are not produced by the pipeline.

Run from the repository root or from paper/:

    python paper/figures/make_figures.py

This writes:
  - architecture.pdf      The hybrid GNN-LLM architecture block diagram.
  - confusion_matrix.png  A representative test-split confusion matrix that
                          matches the counts reported in Section VII. The
                          authoritative confusion matrix is regenerated by
                          the pipeline at code/scripts/06_evaluate.py.
"""
from __future__ import annotations

from pathlib import Path

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

OUT = Path(__file__).resolve().parent


def make_architecture() -> None:
    fig, ax = plt.subplots(figsize=(9, 4.5))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 5)
    ax.axis("off")

    def box(x, y, w, h, text, fc="#e7f5ff", ec="#1c7ed6"):
        rect = mpatches.FancyBboxPatch(
            (x, y), w, h, boxstyle="round,pad=0.05",
            linewidth=1.4, edgecolor=ec, facecolor=fc,
        )
        ax.add_patch(rect)
        ax.text(x + w / 2, y + h / 2, text, ha="center", va="center", fontsize=9)

    def arrow(x1, y1, x2, y2):
        ax.annotate(
            "", xy=(x2, y2), xytext=(x1, y1),
            arrowprops=dict(arrowstyle="->", lw=1.2, color="#495057"),
        )

    box(0.2, 3.6, 1.8, 0.7, "BENIGN_ADDRESSES\n(210 contracts)", fc="#d3f9d8", ec="#2f9e44")
    box(0.2, 2.4, 1.8, 0.7, "FRAUD_ADDRESSES\n(seed + Forta)", fc="#ffe3e3", ec="#c92a2a")
    box(2.6, 3.0, 1.8, 1.4, "Data Collection\n(BigQuery,\nForta, Etherscan)")
    box(4.8, 3.0, 1.8, 1.4, "Preprocessing\n(DuckDB joins,\nPyG graph)")
    box(7.0, 3.6, 2.6, 0.9, "GraphSAGE\n(3 -> 128 -> 64)", fc="#fff3bf", ec="#fab005")
    box(7.0, 2.4, 2.6, 0.9, "CodeBERT (frozen)\n(768-dim pooler)", fc="#fff3bf", ec="#fab005")
    box(7.0, 0.7, 2.6, 1.2, "Fusion (832 -> 128)\nClassifier (-> 2)", fc="#e7f5ff", ec="#1c7ed6")

    arrow(2.0, 4.0, 2.6, 3.9)
    arrow(2.0, 2.7, 2.6, 3.5)
    arrow(4.4, 3.7, 4.8, 3.7)
    arrow(6.6, 4.0, 7.0, 4.0)
    arrow(6.6, 3.4, 7.0, 2.9)
    arrow(8.3, 3.6, 8.3, 1.9)
    arrow(8.3, 2.4, 8.3, 1.9)

    ax.text(
        5.0, 4.7, "Hybrid GNN-LLM Fraud Detection Architecture",
        ha="center", va="center", fontsize=11, fontweight="bold",
    )
    fig.savefig(OUT / "architecture.pdf", bbox_inches="tight", dpi=200)
    plt.close(fig)


def make_confusion_matrix() -> None:
    cm = np.array([[154, 7], [11, 18]])
    fig, ax = plt.subplots(figsize=(5, 4))
    sns.heatmap(
        cm, annot=True, fmt="d", cmap="Blues",
        xticklabels=["Benign", "Fraud"],
        yticklabels=["Benign", "Fraud"],
        cbar=False, ax=ax,
    )
    ax.set_xlabel("Predicted Label")
    ax.set_ylabel("True Label")
    ax.set_title("Confusion Matrix (Test Split)")
    fig.tight_layout()
    fig.savefig(OUT / "confusion_matrix.png", bbox_inches="tight", dpi=200)
    plt.close(fig)


if __name__ == "__main__":
    make_architecture()
    make_confusion_matrix()
    print(f"Figures written to {OUT}")
